name: Build and Release libcurl-l10n

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gettext rpm cmake

      - name: Run build-all.sh
        run: |
          chmod +x build-all.sh
          ./build-all.sh

      - name: Collect build artifacts
        run: |
          mkdir -p artifacts
          find . -type f \( -name "*.deb" -o -name "*.rpm" \) -exec mv {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcurl-l10n-packages
          path: artifacts/
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.deb
            artifacts/*.rpm
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
